logging:
  level:
    com:
      dayup:
        seckill: debug

#\u670D\u52A1\u5668\u914D\u7F6E
server:
  port: 8081
  servlet:
    encoding:
      charset: utf-8

#mybatis\u914D\u7F6E
mybatis:
  type-aliases-package: com.dayup.seckill.entities

#mysql\u6570\u636E\u6E90
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    url: jdbc:mysql://120.78.201.5:3306/seckill?serverTimezone=Asia/Shanghai
    username: root
  redis:
    host: 120.78.201.5
    port: 6379
