logging:
  level:
    com:
      dayup:
        seckill: debug

#Server配置
server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      force: true

#mybatis配置
mybatis:
  type-aliases-package: com.dayup.seckill.entities
  configuration:
    map-underscore-to-camel-case: true

spring:
  #数据源连接池配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    url: jdbc:mysql://120.78.201.5:3306/seckill?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=UTF-8
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 10
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      filters: stat,wall
  #Redis配置
  redis:
    host: 120.78.201.5
    port: 6379
  #Redis解决分布式Session
  session:
    store-type: redis
  #RaabitMQ消息队列配置
  rabbitmq:
    host: 120.78.201.5
    port: 5672
    username: admin
    password: admin
