logging:
  level:
    com:
      dayup:
        seckill: debug

#Server配置
server:
  port: 8082
  servlet:
    encoding:
      charset: utf-8

#mybatis配置
mybatis:
  type-aliases-package: com.dayup.seckill.entities
  configuration:
    map-underscore-to-camel-case: true

spring:
  #数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    url: jdbc:mysql://120.78.201.5:3306/seckill?serverTimezone=Asia/Shanghai
    username: root
  #Redis配置
  redis:
    host: 120.78.201.5
    port: 6379
  #Redis解决分布式Session
  session:
    store-type: redis
